### ISSUE TITLE
Missing fast path for small integers

### ISSUE THREAD

**Issue by plokhotnyuk** [dtolnay/ryu#13]
It seems that this repo has already diverged from the C code, at least for the following improvement:
https://github.com/abolz/ryu/commit/c3c5641b7ea0a553d9902328659ba1df85a24992

**Comment by dtolnay** [comment]
I deleted d2s_buffered_n in f02fa5f4eed38b2e18e7de8101fbfeb097a07c45 so that improvement is in code that is no longer included in the Rust version. It looks like the improvement is specific to the way that their formatting handles small integers in exponential notation like `1E4`, so it is not useful for our formatting which would be `10000`.
